### ISSUE TITLE
Installation with python3

### ISSUE THREAD

**Issue by hnadeem2** [hernanchavezthielemann/GRO2LAM#52]
The python3 compatible version doesnt seem to produce the run exe file.
Traceback (most recent call last):
  File "/Users/hassannadeem/RA/gro2lam/GRO2LAM-py3_compatibility/setup", line 12, in <module>
    from lib.misc.file import write_xfile, fileseeker, check_file, p_sep
  File "/Users/hassannadeem/RA/gro2lam/GRO2LAM-py3_compatibility/lib/misc/file.py", line 6, in <module>
    from lib.misc.warn import wrg_1, wrg_3, pop_wrg_1
  File "/Users/hassannadeem/RA/gro2lam/GRO2LAM-py3_compatibility/lib/misc/warn.py", line 5, in <module>
    from lib.gui.popup import message_box
  File "/Users/hassannadeem/RA/gro2lam/GRO2LAM-py3_compatibility/lib/gui/popup.py", line 5, in <module>
    from lib.gui.tk_lib import Frame, Toplevel, Label, Button, Checkbutton, Entry
  File "/Users/hassannadeem/RA/gro2lam/GRO2LAM-py3_compatibility/lib/gui/tk_lib.py", line 12, in <module>
    from tkinter import Tk, Frame, Label, TclError, PhotoImage, Toplevel
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

**Comment by hernanchavezthielemann** [comment]
Hello @hassanuiuc,
Not a bug, you need to have a system to run GRO2LAM first.

Seems like you are missing tkinter # import _tkinter # If this fails your Python may not be configured for Tk
look in google for: tkinter install <Operative system> <Python version>

best,
Hernan.
